Fix missing sounddevice module
huggingface/speech-to-speech pull request #7
Opened 2024-08-15 19:13 UTC by AlexHayton

Without this I get the following:

```
$ python listen_and_play.py --host localhost

Traceback (most recent call last):
  File "/Users/alex.hayton/funtime/speech-to-speech/listen_and_play.py", line 6, in <module>
    import sounddevice as sd
ModuleNotFoundError: No module named 'sounddevice'
```

2024-08-18 17:02 UTC, andimarafioti requested changes
Great suggestion! let's specify the version number and merge this one 👍

2024-08-18 17:02 UTC, andimarafioti commented on requirements.txt
> +sounddevice
```suggestion
sounddevice==0.5.0
```

2024-08-18 17:02 UTC, andimarafioti commented on requirements.txt
> +sounddevice
I would specify the version number to stay consistent.

2024-08-18 22:43 UTC, AlexHayton commented
@andimarafioti Great! Version number updated

2024-08-19 08:25 UTC, andimarafioti approved these changes
awesome! thanks!

2024-08-19 08:25 UTC, merged