feat:Add rest call support similar to oepn-api style
huggingface/speech-to-speech pull request #81
Opened 2024-09-04 13:35 UTC by wuhongsheng

2024-09-04 16:28 UTC, andimarafioti commented
You're such a goat! Thank you 🙏 
With which base_url were you testing this? for me to reproduce

2024-09-05 00:18 UTC, wuhongsheng commented
> You're such a goat! Thank you 🙏 With which base_url were you testing this? for me to reproduce

I tested it with deepseek url

from openai import OpenAI

client = OpenAI(api_key="<DeepSeek API Key>", base_url="https://api.deepseek.com")

response = client.chat.completions.create(
    model="deepseek-chat",
    messages=[
        {"role": "system", "content": "You are a helpful assistant"},
        {"role": "user", "content": "Hello"},
    ],
    stream=False
)

print(response.choices[0].message.content)

2024-09-06 13:27 UTC, MattiPaivike commented
Yes, for this to be useful it should stream the text from the API and create TTS for each chunked text stream. Too much lag if you have to wait for generation of the entire message.

There is an example of how streaming can be implemented in OpenAI Python library:
https://github.com/openai/openai-python?tab=readme-ov-file#streaming-responses

2024-09-06 15:51 UTC, eustlb requested changes
Great work, thanks @wuhongsheng ! 🙏🤗
This will definitely meet a relevant use case.
Almost ready to merge, it just needs to handle the `--open_api_stream` flag. The suggestion given below to handle it has been tested using `--whisper_mlx` and `--melo`, works fine.

2024-09-06 15:51 UTC, eustlb commented on arguments_classes/open_api_language_model_arguments.py
> +        default="你是一位乐于助人且友好的 AI 助手。您彬彬有礼、尊重他人.",
Let's stick with a default initial chat prompt in english. 

```suggestion
        default="You are a helpful and friendly AI assistant. You are polite, respectful, and aim to provide concise responses of less than 20 words.",
```

2024-09-06 15:51 UTC, eustlb commented on LLM/openai_api_language_model.py
> +        yield generated_text
Let's handle streaming as done in [language_model.py](https://github.com/huggingface/speech-to-speech/blob/d98e25276976c16e6881b01dc4dfb625021e9291/LLM/language_model.py#L113C5-L144C46)

```suggestion
def process(self, prompt):
        logger.debug("call api language model...")
        self.chat.append({"role": self.user_role, "content": prompt})

        language_code = None
        if isinstance(prompt, tuple):
            prompt, language_code = prompt

        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": self.user_role, "content": prompt},
            ],
            stream=self.stream
        )
        if self.stream:
            generated_text, printable_text = "", ""
            for chunk in response:
                new_text = chunk.choices[0].delta.content or ""
                generated_text += new_text
                printable_text += new_text
                sentences = sent_tokenize(printable_text)
                if len(sentences) > 1:
                    yield sentences[0], language_code
                    printable_text = new_text
            self.chat.append({"role": "assistant", "content": generated_text})
            # don't forget last sentence
            yield printable_text, language_code
        else:
            generated_text = response.choices[0].message.content
            self.chat.append({"role": "assistant", "content": generated_text})
            yield generated_text, language_code
```

2024-09-07 07:47 UTC, wuhongsheng reviewed
add sent_tokenize

2024-09-07 07:47 UTC, wuhongsheng commented on LLM/openai_api_language_model.py
> +
from nltk import sent_tokenize

2024-09-18 05:19 UTC, wuhongsheng reviewed
is OK

2024-09-18 12:06 UTC, eustlb commented
Hey @wuhongsheng, thanks for iterating. Nevertheless, you have not committed [suggested changes](https://github.com/huggingface/speech-to-speech/pull/81#discussion_r1747333293) to handle the `--open_api_stream` flag, can you do so ? After that, we'll be able to merge 👌

2024-09-19 22:30 UTC, wuhongsheng reviewed
is ok

2024-09-20 08:31 UTC, eustlb commented
LGTM! Thanks for the good work 🤗

2024-09-20 08:31 UTC, merged